spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
  main:
    banner-mode: console
  application:
    name: Fantastic Gradle API
    version: 0.0.1-SNAPSHOT
    fantastic-gradle-version: 1.0.0-SNAPSHOT

logging:
  level:
    root: INFO
    com.leonovich.fantasticgradle: DEBUG
    org.springframework: INFO

springdoc:
#  api-docs:
#    path: /api-docs # setup custom path for swagger api docs
   swagger-ui:
     operations-sorter: method