name: Run Gradle on PRs
'on':
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop ]
jobs:
  gradle:
    strategy:
      matrix:
        os:
          #- ubuntu-latest
          - macos-latest
          #- windows-latest
    runs-on: ${{ matrix.os }}

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17

      - name: setup gradle
        uses: gradle/gradle-build-action@v2

      - name: execute gradle build
        run: ./gradlew build
